/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku.solver;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author girig
 */
public class SudokuLayout extends javax.swing.JFrame{

    /**
     * Creates new form SudokuLayout
     */
    SudokuSolver s = new SudokuSolver();
    int[][] data = s.createBoard();
    int[][] userInputData = data;
    JPanel box;  
    JPanel board;
    JPanel buttonPanel;
    static JFrame f;
    JButton solve;
    JButton reset;
    boolean solved = false;
    JButton time;
    Thread t = null;
    
    public SudokuLayout() {
        //initComponents();
        f = new JFrame("Sudoku");
        setBackground(Color.MAGENTA);
        
        board = new JPanel();
        board.setLayout(new GridLayout(3, 3));
        board.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        board.setBorder(new EmptyBorder(15, 15, 15, 15));   
     
        buttonPanel = new JPanel();
        reset = new JButton("Reset");
        solve = new JButton("Solve");       
        buttonPanel.add(reset);
        buttonPanel.add(solve); 
        buttonPanel.setBorder(new EmptyBorder(5, 5, 10, 5));
       
        new TimerSetter(5);
       t.startTime();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public void setLayout(){
        f.add(board,BorderLayout.CENTER );
        f.add(buttonPanel, BorderLayout.SOUTH);
        
        f.setSize(500, 500);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setVisible(true);
    }
    
   
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}